### ISSUE TITLE
Panic running cephfs-provisioner

### ISSUE THREAD

**Issue by jhou1** [rootfs/cephfs-provisioner#2]
The program cephfs-provisioner panics during `docker run`.

## Versions
```
[root@k8s ~]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Thu Feb 23 11:52:33 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Thu Feb 23 11:52:33 2017
 OS/Arch:         linux/amd64
[root@k8s ~]# go version
go version go1.8 linux/amd64

[root@k8s ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```

```
[root@k8s ~]# docker run -ti -v /root/.kube:/kube --privileged --net=host  cephfs-provisioner /usr/local/bin/cephfs-provisioner -master=http://127.0.0.1:8080 -kubeconfig=/kube/config
/usr/local/bin/cephfs-provisioner flag redefined: log_dir
panic: /usr/local/bin/cephfs-provisioner flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420052060, 0x1d13020, 0xc4200164c0, 0x14cac30, 0x7, 0x14f2de6, 0x2f)
        /usr/local/go/src/flag/flag.go:793 +0x420
flag.(*FlagSet).StringVar(0xc420052060, 0xc4200164c0, 0x14cac30, 0x7, 0x0, 0x0, 0x14f2de6, 0x2f)
        /usr/local/go/src/flag/flag.go:696 +0x8b
flag.(*FlagSet).String(0xc420052060, 0x14cac30, 0x7, 0x0, 0x0, 0x14f2de6, 0x2f, 0xc4200164b0)
        /usr/local/go/src/flag/flag.go:709 +0x90
flag.String(0x14cac30, 0x7, 0x0, 0x0, 0x14f2de6, 0x2f, 0x1388580)
        /usr/local/go/src/flag/flag.go:716 +0x69
github.com/rootfs/cephfs-provisioner/vendor/k8s.io/client-go/vendor/github.com/golang/glog.init()
        /root/go/src/github.com/rootfs/cephfs-provisioner/vendor/k8s.io/client-go/vendor/github.com/golang/glog/glog_file.go:41 +0x14a
github.com/rootfs/cephfs-provisioner/vendor/k8s.io/client-go/pkg/labels.init()
        /root/go/src/github.com/rootfs/cephfs-provisioner/vendor/k8s.io/client-go/pkg/labels/selector.go:836 +0x64
github.com/rootfs/cephfs-provisioner/vendor/k8s.io/client-go/pkg/api/unversioned.init()
        /root/go/src/github.com/rootfs/cephfs-provisioner/vendor/k8s.io/client-go/pkg/api/unversioned/zz_generated.deepcopy.go:391 +0x8c
github.com/rootfs/cephfs-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/leaderelection/resourcelock.init()
        /root/go/src/github.com/rootfs/cephfs-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/leaderelection/resourcelock/provisionpvclock.go:93 +0x44
github.com/rootfs/cephfs-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/leaderelection.init()
        /root/go/src/github.com/rootfs/cephfs-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/leaderelection/leaderelection.go:291 +0x53
github.com/rootfs/cephfs-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.init()
        /root/go/src/github.com/rootfs/cephfs-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/volume.go:70 +0x6b
main.init()
        /root/go/src/github.com/rootfs/cephfs-provisioner/cephfs-provisioner.go:307 +0x6e
```

**Comment by rootfs** [comment]
@jhou1 thanks for testing. I reverted the vendor packages, it should be fine now.
