### ISSUE TITLE
CephFS ProvisioningFailed, 'no volume plugin matched'

### ISSUE THREAD

**Issue by jhou1** [rootfs/cephfs-provisioner#3]
Use the example class.yaml and claim.yaml, provision failed with following error:

```
[root@k8s cephfs-provisioner]# kubectl describe pvc claim1
Name:           claim1
Namespace:      default
StorageClass:   cephfs
Status:         Pending
Volume:
Labels:         <none>
Annotations:    control-plane.alpha.kubernetes.io/leader={"holderIdentity":"b2090293-087c-11e7-b070-0050569f3e08","leaseDurationSeconds":15,"acquireTime":"2017-03-14T07:38:55Z","renewTime":"2017-03-14T07:39:25Z","lea...
                volume.beta.kubernetes.io/storage-class=cephfs
Capacity:
Access Modes:
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  37s           0s              8       persistentvolume-controller                     Warning         ProvisioningFailed      no volume plugin matched
```

The cephfs-provisioner logged

```
I0314 07:43:23.340458       1 controller.go:841] scheduleOperation[lock-provision-default/claim1[46eff3fb-0889-11e7-ae11-0050569f3e08]]   [8/14989]
I0314 07:43:23.374992       1 leaderelection.go:157] attempting to acquire leader lease...
I0314 07:43:23.395569       1 leaderelection.go:179] sucessfully acquired lease to provision for pvc default/claim1
I0314 07:43:23.395925       1 controller.go:841] scheduleOperation[provision-default/claim1[46eff3fb-0889-11e7-ae11-0050569f3e08]]
I0314 07:43:25.435182       1 leaderelection.go:199] stopped trying to renew lease to provision for pvc default/claim1, task failed
I0314 07:43:38.341383       1 controller.go:841] scheduleOperation[provision-default/claim1[46eff3fb-0889-11e7-ae11-0050569f3e08]]
I0314 07:43:53.343080       1 controller.go:841] scheduleOperation[lock-provision-default/claim1[46eff3fb-0889-11e7-ae11-0050569f3e08]]
I0314 07:43:53.384710       1 leaderelection.go:157] attempting to acquire leader lease...
I0314 07:43:53.403278       1 leaderelection.go:179] sucessfully acquired lease to provision for pvc default/claim1
I0314 07:43:53.403482       1 controller.go:841] scheduleOperation[provision-default/claim1[46eff3fb-0889-11e7-ae11-0050569f3e08]]
I0314 07:43:55.424446       1 leaderelection.go:199] stopped trying to renew lease to provision for pvc default/claim1, task failed
E0314 07:43:55.644437       1 cephfs-provisioner.go:82] failed to provision share "kubernetes-dynamic-pvc-46fcf89e-0889-11e7-b070-0050569f3e08" for
 "kubernetes-dynamic-user-46fcf9e1-0889-11e7-b070-0050569f3e08", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 253, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 247, in main
    print cephfs.create_share(share, user)    
  File "/usr/local/bin/cephfs_provisioner", line 191, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 86, in volume_client
    self._volume_client.connect(None)
  File "/usr/lib/python2.7/site-packages/ceph_volume_client.py", line 458, in connect
    self.rados.connect()
  File "rados.pyx", line 785, in rados.Rados.connect (rados.c:8969)
rados.TimedOut: error connecting to the cluster
```

**Comment by jhou1** [comment]
BTW there is a typo from leaderelection.go

```
I0314 07:43:23.395569       1 leaderelection.go:179] sucessfully acquired lease to provision for pvc default/claim1
```

`sucessfully` -> `successfully`

**Comment by rootfs** [comment]
@jhou1 nice catch! The typo is from vendor code.

The `class.yaml` uses a mon IP that is based on my setup, you probably have to check if that IP is also your ceph mon's IP.

**Comment by jhou1** [comment]
Sorry for the delay. I probably configured something wrong. The problem is gone now.
